name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build Binary for Linux
      run: GOOS=linux GOARCH=amd64 go build -o wp-wingman main.go

    - name: Build Binary for Windows
      run: GOOS=windows GOARCH=amd64 go build -o wp-wingman.exe main.go

    - name: Build Binary for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o wp-wingman main.go
