name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Binary for Linux
      run: GOOS=linux GOARCH=amd64 go build -o wp-wingman-linux-amd64 main.go

    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "wp-wingman-linux-amd64"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
