name: Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Binary for Linux
      run: GOOS=linux GOARCH=amd64 go build -o wp-wingman-linux-amd64 main.go

    - name: Test
      run: go test -v ./...

   
